version: 2

sources:
  - name: stock_analysis
    database: meta-sanctum-461903-p3
    tables:
      - name: combined_tickers
      - name: fred
      - name: stock_info
      - name: techincal_indicator
